export const sharbiFunAbi = [
	{ type: 'constructor', inputs: [], stateMutability: 'nonpayable' },
	{ type: 'fallback', stateMutability: 'payable' },
	{ type: 'receive', stateMutability: 'payable' },
	{
		type: 'function',
		name: 'K',
		inputs: [{ name: '', type: 'address', internalType: 'address' }],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'MAX_TOTAL_SUPPLY',
		inputs: [],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'X0',
		inputs: [{ name: '', type: 'address', internalType: 'address' }],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'X1',
		inputs: [{ name: '', type: 'address', internalType: 'address' }],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'Y0',
		inputs: [{ name: '', type: 'address', internalType: 'address' }],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'Y1',
		inputs: [{ name: '', type: 'address', internalType: 'address' }],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'dexRouter',
		inputs: [],
		outputs: [{ name: '', type: 'address', internalType: 'address' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'donationAddress',
		inputs: [],
		outputs: [{ name: '', type: 'address', internalType: 'address' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'donationAmount',
		inputs: [{ name: '', type: 'address', internalType: 'address' }],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'donationRate',
		inputs: [],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'feeTo',
		inputs: [],
		outputs: [{ name: '', type: 'address', internalType: 'address' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'getOutEthAmount',
		inputs: [
			{ name: 'tokenAddress', type: 'address', internalType: 'address' },
			{ name: 'tokenAmount', type: 'uint256', internalType: 'uint256' },
		],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'getOutTokenAmount',
		inputs: [
			{ name: 'tokenAddress', type: 'address', internalType: 'address' },
			{ name: 'ethAmount', type: 'uint256', internalType: 'uint256' },
		],
		outputs: [
			{ name: '', type: 'bool', internalType: 'bool' },
			{ name: '', type: 'uint256', internalType: 'uint256' },
		],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'graduate',
		inputs: [
			{ name: 'tokenAddress', type: 'address', internalType: 'address' },
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'graduateFeeRate',
		inputs: [],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'initialize',
		inputs: [
			{ name: '_dexRouter', type: 'address', internalType: 'address' },
			{ name: '_operator', type: 'address', internalType: 'address' },
			{ name: '_feeTo', type: 'address', internalType: 'address' },
			{ name: '_donationAddress', type: 'address', internalType: 'address' },
			{ name: '_tradingFeeRate', type: 'uint256', internalType: 'uint256' },
			{ name: '_graduateFeeRate', type: 'uint256', internalType: 'uint256' },
			{ name: '_donationRate', type: 'uint256', internalType: 'uint256' },
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'launch',
		inputs: [
			{ name: 'name', type: 'string', internalType: 'string' },
			{ name: 'symbol', type: 'string', internalType: 'string' },
			{ name: 'totalSupply', type: 'uint256', internalType: 'uint256' },
			{
				name: '_curveSize',
				type: 'uint8',
				internalType: 'enum SharbiFun.CurveSize',
			},
			{ name: 'makeDonation', type: 'bool', internalType: 'bool' },
		],
		outputs: [],
		stateMutability: 'payable',
	},
	{
		type: 'function',
		name: 'operator',
		inputs: [],
		outputs: [{ name: '', type: 'address', internalType: 'address' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'owner',
		inputs: [],
		outputs: [{ name: '', type: 'address', internalType: 'address' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'renounceOwnership',
		inputs: [],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'sell',
		inputs: [
			{ name: 'tokenAddress', type: 'address', internalType: 'address' },
			{ name: 'amountIn', type: 'uint256', internalType: 'uint256' },
			{ name: 'amountOutMin', type: 'uint256', internalType: 'uint256' },
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'setDonationAddress',
		inputs: [
			{
				name: 'newDonationAddress',
				type: 'address',
				internalType: 'address',
			},
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'setDonationRate',
		inputs: [
			{ name: 'newDonationRate', type: 'uint256', internalType: 'uint256' },
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'setFeeTo',
		inputs: [{ name: 'newFeeTo', type: 'address', internalType: 'address' }],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'setGraduateFeeRate',
		inputs: [
			{
				name: 'newGraduateFeeRate',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'setOperator',
		inputs: [{ name: 'newOperator', type: 'address', internalType: 'address' }],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'setTradingFeeRate',
		inputs: [{ name: 'newFeeRate', type: 'uint256', internalType: 'uint256' }],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'setWhitelistedToken',
		inputs: [
			{ name: 'token', type: 'address', internalType: 'address' },
			{ name: 'isWhitelisted', type: 'bool', internalType: 'bool' },
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'swapAndBuy',
		inputs: [
			{ name: 'funTokenAddress', type: 'address', internalType: 'address' },
			{ name: 'paymentToken', type: 'address', internalType: 'address' },
			{ name: 'amountIn', type: 'uint256', internalType: 'uint256' },
			{ name: 'minBoneOut', type: 'uint256', internalType: 'uint256' },
			{ name: 'minFunTokenOut', type: 'uint256', internalType: 'uint256' },
		],
		outputs: [],
		stateMutability: 'payable',
	},
	{
		type: 'function',
		name: 'tokenList',
		inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		outputs: [{ name: '', type: 'address', internalType: 'address' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'tokenStates',
		inputs: [{ name: '', type: 'address', internalType: 'address' }],
		outputs: [
			{ name: '', type: 'uint8', internalType: 'enum SharbiFun.TokenState' },
		],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'tokenSupply',
		inputs: [{ name: '', type: 'address', internalType: 'address' }],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'totalTokenCount',
		inputs: [],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'tradingFeeRate',
		inputs: [],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'transferOwnership',
		inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'virtualX',
		inputs: [{ name: '', type: 'address', internalType: 'address' }],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'virtualY',
		inputs: [{ name: '', type: 'address', internalType: 'address' }],
		outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'whitelistedTokens',
		inputs: [{ name: '', type: 'address', internalType: 'address' }],
		outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
		stateMutability: 'view',
	},
	{
		type: 'event',
		name: 'Buy',
		inputs: [
			{
				name: 'tokenAddress',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'buyer',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'ethAmountIn',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'tokenAmountOut',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'Complete',
		inputs: [
			{
				name: 'tokenAddress',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'Donation',
		inputs: [
			{
				name: 'tokenAddress',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'donor',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'amount',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'Graduate',
		inputs: [
			{
				name: 'pairAddress',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'tokenAddress',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'ethAmount',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'tokenAmount',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'Initialized',
		inputs: [
			{
				name: 'version',
				type: 'uint64',
				indexed: false,
				internalType: 'uint64',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'Launch',
		inputs: [
			{
				name: 'tokenAddress',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'launcher',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'name',
				type: 'string',
				indexed: false,
				internalType: 'string',
			},
			{
				name: 'symbol',
				type: 'string',
				indexed: false,
				internalType: 'string',
			},
			{
				name: 'totalSupply',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'curveSize',
				type: 'uint8',
				indexed: false,
				internalType: 'enum SharbiFun.CurveSize',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'OwnershipTransferred',
		inputs: [
			{
				name: 'previousOwner',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'newOwner',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'Sell',
		inputs: [
			{
				name: 'tokenAddress',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'seller',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'tokenAmountIn',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'ethAmountOut',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'SetDonationAddress',
		inputs: [
			{
				name: 'donationAddress',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'SetDonationRate',
		inputs: [
			{
				name: 'donationRate',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'SetFeeTo',
		inputs: [
			{
				name: 'feeTo',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'SetGraduateFee',
		inputs: [
			{
				name: 'graduateFee',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'SetOperator',
		inputs: [
			{
				name: 'operator',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'SetTradingFeeRate',
		inputs: [
			{
				name: 'tradingFeeRate',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'WhitelistToken',
		inputs: [
			{
				name: 'token',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'isWhitelisted',
				type: 'bool',
				indexed: false,
				internalType: 'bool',
			},
		],
		anonymous: false,
	},
	{
		type: 'error',
		name: 'AddressEmptyCode',
		inputs: [{ name: 'target', type: 'address', internalType: 'address' }],
	},
	{
		type: 'error',
		name: 'AddressInsufficientBalance',
		inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
	},
	{ type: 'error', name: 'EmptyName', inputs: [] },
	{ type: 'error', name: 'EmptySymbol', inputs: [] },
	{ type: 'error', name: 'FailedInnerCall', inputs: [] },
	{ type: 'error', name: 'InsufficientOutputAmount', inputs: [] },
	{
		type: 'error',
		name: 'InvalidAddress',
		inputs: [
			{ name: 'field', type: 'string', internalType: 'string' },
			{ name: 'value', type: 'address', internalType: 'address' },
		],
	},
	{
		type: 'error',
		name: 'InvalidAmount',
		inputs: [
			{ name: 'field', type: 'string', internalType: 'string' },
			{ name: 'value', type: 'uint256', internalType: 'uint256' },
		],
	},
	{
		type: 'error',
		name: 'InvalidFeeRate',
		inputs: [
			{ name: 'field', type: 'string', internalType: 'string' },
			{ name: 'value', type: 'uint256', internalType: 'uint256' },
		],
	},
	{ type: 'error', name: 'InvalidInitialization', inputs: [] },
	{
		type: 'error',
		name: 'InvalidTokenState',
		inputs: [
			{ name: 'tokenAddress', type: 'address', internalType: 'address' },
			{
				name: 'expectedState',
				type: 'uint8',
				internalType: 'enum SharbiFun.TokenState',
			},
		],
	},
	{ type: 'error', name: 'NotInitializing', inputs: [] },
	{ type: 'error', name: 'NotOperator', inputs: [] },
	{
		type: 'error',
		name: 'OwnableInvalidOwner',
		inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
	},
	{
		type: 'error',
		name: 'OwnableUnauthorizedAccount',
		inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
	},
	{ type: 'error', name: 'ReentrancyGuardReentrantCall', inputs: [] },
	{
		type: 'error',
		name: 'SafeERC20FailedOperation',
		inputs: [{ name: 'token', type: 'address', internalType: 'address' }],
	},
	{ type: 'error', name: 'SwapFailed', inputs: [] },
	{
		type: 'error',
		name: 'TokenNotWhitelisted',
		inputs: [{ name: 'token', type: 'address', internalType: 'address' }],
	},
] as const
