import type { Metadata } from 'next';
import { IBM_Plex_Mono } from 'next/font/google';
import './globals.css';
import { ReduxProvider } from '@/redux/redux-provider';
import MainLayout from '@/components/layouts/main-layout';
import { headers } from 'next/headers'; // added
import ContextProvider from '@/context';

const ibmPlexMono = IBM_Plex_Mono({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Sharbi Fun',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookies = headers().get('cookie');

  return (
    <html lang='en'>
      <body className={ibmPlexMono.className + ' dark'}>
        <ContextProvider cookies={cookies}>
          <ReduxProvider>
            <MainLayout>{children}</MainLayout>
          </ReduxProvider>
        </ContextProvider>
      </body>
    </html>
  );
}
