import type { Metadata } from 'next';
import { IBM_Plex_Mono } from 'next/font/google';
import './globals.css';
import { ReduxProvider } from '@/redux/redux-provider';
import MainLayout from '@/components/layouts/main-layout';
import { WalletProvider } from '@/context/WalletContext';

const ibmPlexMono = IBM_Plex_Mono({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Sharbi Fun',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={ibmPlexMono.className + ' dark'}>
        <WalletProvider>
        <ReduxProvider>
          <MainLayout>{children}</MainLayout>
        </ReduxProvider>
        </WalletProvider>
      </body>
    </html>
  );
}
